# Run with ansible-playbook -K to setup passwordless sudo
- name: Configure the ssh user for ansible to use passwordless sudo
  hosts: all
  become: true
  gather_facts: no
  vars:
    sudo_user: student
  tasks:
  - name: Create sudoers config to allow {{ sudo_user }} to use passwordless sudo
    copy:
      dest: /etc/sudoers.d/student
      content: "{{ sudo_user }}    ALL=(ALL)   NOPASSWD: ALL"

