# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
- name: Play to install kubeadm and kubelet
  hosts: masters,workers
  become: true
  vars:
  gather_facts: false
  tasks:
  - name: Ensure neccessary kernel modules loaded
    modprobe:
      name: "{{ item }}"
      state: present
    loop:
    - br_netfilter

  - name: Ensure sysctl parameters set
    sysctl:
      name: "{{ item }}" 
      value: "1"
      sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    loop:
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-ip6tables
    
  # to add firewalld module to configure firewall

  - name: Setup repo file for installing kubeadm and kubelet
    copy: 
      content: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        exclude=kubelet kubeadm kubectl
      dest: /etc/yum.repos.d/kubernetes.repo

  - name: Put SELinux in permissive mode, logging actions that would be blocked.
    selinux:
      policy: targeted
      state: permissive

  - name: Ensure kubelet,kubeadm and kubectl are installed
    yum: 
      name: 
      - kubelet 
      - kubeadm 
      - kubectl
      state: latest
      disable_excludes: kubernetes

  - name: Ensure systemd reloads and crio is started and enabled
    systemd:
      state: started
      enabled: true
      daemon_reload: yes
      name: kubelet
